# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

before_install:
  - tlmgr install tcolorbox
sudo: true
cache: packages

r_packages:
  - covr

addons:
  apt:
    packages:
      - ghostscript

matrix:
  allow_failures:
    - R: devel

after_success:
  - Rscript -e 'library(covr); codecov()'
