# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

r:
  - oldrel
  - release
  - devel

os:
  - linux

before_install:
  - tlmgr install tcolorbox
sudo: false
cache: packages

r_packages:
  - covr

addons:
  apt:
    packages:
      - ghostscript

after_success:
  - Rscript -e 'library(covr); codecov()'
