# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

before_install:
  - if [[ "$OSTYPE" != "linux-gnu" ]]; then sudo tlmgr install tcolorbox; fi

sudo: true
cache: packages

r_packages:
  - covr

addons:
  apt:
    packages:
      - ghostscript

matrix:
  allow_failures:
    - r: devel

after_success:
  - Rscript -e 'library(covr); codecov()'
